server:
  # 将端口由9527改为80,使请求没有端口号
  # 较小的端口号(如80)在Ubuntu下需要权限
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-zuul-gateway
    prefer-ip-address: true


zuul:
  routes:
      # 对各模块进行转发
      # 登录模块
      login-service:
        path: /hyapi/common/**
        serviceId: microservicecloud-login
        sensitiveHeaders: "*"
      # 产品模块
      product-service:
        path: /hyapi/admin/business/product/**
        serviceId: microservicecloud-product
        sensitiveHeaders: "*"
      # 文件上传模块
      upload-service:
        path: /hyapi/resource/**
        serviceId: microservicecloud-upload
      # 供应商模块
      supplier-service:
        path: /hyapi/admin/business/provider/**
        serviceId: microservicecloud-supplier
        sensitiveHeaders: "*"
      # 订单模块
      order-service:
        path: /hyapi/admin/business/order/**
        serviceId: microservicecloud-order
        sensitiveHeaders: "*"
      # 商城模块
      ymym-service:
        path: /hyapi/ymym/**
        serviceId: microservicecloud-ymym
        sensitiveHeaders: "*"
      # 物流模块
      express-service:
        path: /hyapi/admin/inbound/**
        serviceId: microservicecloud-express
        sensitiveHeaders: "*"

  ignoredServices: "*"
  sensitiveHeaders: "*"
#  host:
#      connect-timeout-millis: 20000
#      socket-timeout-millis: 20000

info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$