server:
  # 将端口由9527改为80,使请求没有端口号
  # 较小的端口号(如80)在Ubuntu下需要权限
  port: 9527
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接,默认取CPU核心数量,最小值为2
    io-threads: 1000
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载，默认值为io-threads*8
    worker-threads: 8000

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-zuul-gateway
    prefer-ip-address: true

zuul:
  semaphore:
    max-semaphores: 10000
  host:
    max-per-route-connections: 10000
    max-total-connections: 60000
    socket-timeout-millis: 30000
    connect-timeout-millis: 30000
  routes:
      ignoredServices: "*"
      sensitiveHeaders: "*"
      # 登录模块
      login-service:
        path: /hyapi/common/**
        serviceId: microservicecloud-login
        sensitiveHeaders: "*"
      # 订单模块
      order-service:
        path: /hyapi/admin/business/order/**
        serviceId: microservicecloud-order
        sensitiveHeaders: "*"
      # 产品模块
      product-service:
        ribbon:
          MaxTotalConnecttions: 30000
          MaxConnectionsPerHost: 30000
        path: /hyapi/admin/business/product/**
        serviceId: microservicecloud-product
        sensitiveHeaders: "*"
      # 供应商模块
      supplier-service:
        path: /hyapi/admin/business/provider/**
        serviceId: microservicecloud-supplier
        sensitiveHeaders: "*"
      # 文件上传模块
      upload-service:
        path: /hyapi/resource/**
        serviceId: microservicecloud-upload
      # 商城模块
      ymym-service:
        path: /hyapi/ymym/**
        serviceId: microservicecloud-ymym
        sensitiveHeaders: "*"

hystrix:
  command:
    default:
      execution:
        isolation:
            thread:
              timeoutInMilliseconds: 60000
            strategy: THREAD

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 1
  MaxTotalHttpConnections: 20000
  MaxCOnnectionsPerHost: 10000

info:
  app.name: zmc-microcloud
  company.name: www.zmc.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$