server:
  # 将端口由9527改为80,使请求没有端口号
  # 较小的端口号(如80)在Ubuntu下需要权限
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-zuul-gateway
    prefer-ip-address: true

zuul:
  host:
    max-per-route-connections: 10000
    max-total-connections: 60000
    socket-timeout-millis: 2000
  routes:
      ignoredServices: "*"
      sensitiveHeaders: "*"
      # 登录模块
      login-service:
        path: /hyapi/common/**
        serviceId: microservicecloud-login
        sensitiveHeaders: "*"
      # 订单模块
      order-service:
        path: /hyapi/admin/business/order/**
        serviceId: microservicecloud-order
        sensitiveHeaders: "*"
      # 产品模块
      product-service:
        path: /hyapi/admin/business/product/**
        serviceId: microservicecloud-product
          ribbon:
             MaxTotalConnecttions: 20000
             MaxConnectionsPerHost: 20000
        sensitiveHeaders: "*"
      # 供应商模块
      supplier-service:
        path: /hyapi/admin/business/provider/**
        serviceId: microservicecloud-supplier
        sensitiveHeaders: "*"
      # 文件上传模块
      upload-service:
        path: /hyapi/resource/**
        serviceId: microservicecloud-upload
      # 商城模块
      ymym-service:
        path: /hyapi/ymym/**
        serviceId: microservicecloud-ymym
        sensitiveHeaders: "*"
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$